export const collections = [
  {
    title: 'Top Communities',
    curatedContentType: 'top-communities-by-members',
    communities: [
      'vanila',
      'uiux',
      'frontend-hub',
      'growth-hackers',
      'javascript',
      'startup-space',
      'wekan',
      'uxstore',
      'wireflow',
      'moonly',
      'masters-of-ux',
    ],
  },
  {
    title: 'Design',
    curatedContentType: 'design-communities',
    data: [
      'masters-of-ux',
      'uxstore',
      'uiux',
      'product-design',
      'icon-design',
      'typography',
      'illustrators',
      'design-management',
      'specfm',
      'up-coming',
      'sketchcasts',
      'google-design',
      'design-code',
      'vectors',
      'designhunt',
      'figma',
      'sketch',
      'framer',
      'abstract',
      'invision',
      'principle',
      'compositor',
      'origami-studio',
      'webflow',
      'fuse',
    ],
  },
];
